[package]
name = "atlas-package-metadata-macro"
description = "Atlas Package Metadata Macro"
documentation = "https://docs.rs/atlas-package-metadata-macro"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
toml = { workspace = true }
