[package]
name = "atlas-stable-layout"
description = "Atlas types with stable memory layouts. Internal use only."
documentation = "https://docs.rs/atlas-stable-layout"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
atlas-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
atlas-pubkey = { workspace = true, default-features = false }

[dev-dependencies]
memoffset = { workspace = true }
