[package]
name = "atlas-serialize-utils"
description = "Atlas helpers for reading and writing bytes."
documentation = "https://docs.rs/atlas-serialize-utils"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-instruction-error = { workspace = true }
atlas-pubkey = { workspace = true, default-features = false }
atlas-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
atlas-pubkey = { workspace = true, default-features = false, features = [
    "borsh",
    "serde",
] }
