[package]
name = "atlas-program-memory"
description = "Basic low-level memory operations for Atlas."
documentation = "https://docs.rs/atlas-program-memory"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[target.'cfg(target_os = "atlas")'.dependencies]
atlas-define-syscall = { workspace = true }

[lints]
workspace = true
