[package]
name = "atlas-shred-version"
description = "Calculation of shred versions."
documentation = "https://docs.rs/atlas-shred-version"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-hard-forks = { workspace = true }
atlas-hash = { workspace = true }
atlas-sha256-hasher = { workspace = true }

[lints]
workspace = true
