[package]
name = "atlas-program-entrypoint"
description = "The Atlas BPF program entrypoint supported by the latest BPF loader."
documentation = "https://docs.rs/atlas-program-entrypoint"
version = "3.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

rust-version = "1.81.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-account-info = { workspace = true }
atlas-define-syscall = { workspace = true }
atlas-msg = { workspace = true }
atlas-program-error = { workspace = true }
atlas-pubkey = { workspace = true, default-features = false }
