[package]
name = "atlas-message"
description = "Atlas transaction message types."
documentation = "https://docs.rs/atlas-message"
version = "3.0.1"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde"]
blake3 = ["dep:blake3"]
dev-context-only-utils = ["bincode", "blake3"]
frozen-abi = [
    "dep:atlas-frozen-abi",
    "dep:atlas-frozen-abi-macro",
    "dep:atlas-logger",
    "atlas-address/frozen-abi",
    "atlas-hash/frozen-abi",
    "serde",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:atlas-short-vec",
    "atlas-address/serde",
    "atlas-hash/serde",
]

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["traits-preview"], optional = true }
lazy_static = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
atlas-address = { workspace = true }
atlas-frozen-abi = { workspace = true, optional = true }
atlas-frozen-abi-macro = { workspace = true, optional = true }
atlas-hash = { workspace = true }
atlas-instruction = { workspace = true, features = ["std"] }
atlas-logger = { workspace = true, optional = true }
atlas-sanitize = { workspace = true }
atlas-sdk-ids = { workspace = true }
atlas-short-vec = { workspace = true, optional = true }
atlas-transaction-error = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
borsh = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
atlas-address-lookup-table-interface = { workspace = true, features = ["bincode", "bytemuck"] }
atlas-example-mocks = { path = "../example-mocks" }
atlas-instruction = { workspace = true, features = ["borsh"] }
atlas-instruction-error = { workspace = true }
atlas-message = { path = ".", features = ["dev-context-only-utils"] }
atlas-nonce = { workspace = true }
atlas-system-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }

[lints]
workspace = true
