[package]
name = "atlas-program-pack"
description = "Atlas Pack serialization trait."
documentation = "https://docs.rs/atlas-program-pack"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-program-error = { workspace = true }
