[package]
name = "atlas-seed-phrase"
description = "Atlas functions for generating keypairs from seed phrases."
documentation = "https://docs.rs/atlas-seed-phrase"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hmac = { workspace = true }
pbkdf2 = { workspace = true }
sha2 = { workspace = true }
