[package]
name = "atlas-secp256k1-program"
description = "Instructions for the Atlas Secp256k1 native program."
documentation = "https://docs.rs/atlas-secp256k1-program"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:atlas-instruction",
    "dep:atlas-sdk-ids",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]
bincode = { workspace = true, optional = true }
digest = { workspace = true }
k256 = { workspace = true, features = ["ecdsa-core"] }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
sha3 = { workspace = true }
atlas-instruction = { workspace = true, features = ["std"], optional = true }
atlas-sdk-ids = { workspace = true, optional = true }
atlas-signature = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
atlas-account-info = { workspace = true }
atlas-example-mocks = { path = "../example-mocks" }
atlas-instruction = { workspace = true }
atlas-instructions-sysvar = { workspace = true }
atlas-keccak-hasher = { workspace = true, features = ["sha3"] }
atlas-msg = { workspace = true }
atlas-program-error = { workspace = true }
atlas-secp256k1-program = { path = ".", features = ["bincode"] }
