[package]
name = "atlas-signer"
description = "Abstractions for Atlas transaction signers. See `atlas-keypair` for a concrete implementation."
documentation = "https://docs.rs/atlas-signer"
version = "3.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
atlas-pubkey = { workspace = true }
atlas-signature = { workspace = true }
atlas-transaction-error = { workspace = true }
