[package]
name = "atlas-slot-history"
description = "Types and utilities for the Atlas SlotHistory sysvar."
documentation = "https://docs.rs/atlas-slot-history"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
serde = ["dep:serde", "dep:serde_derive", "bv/serde"]
sysvar = ["dep:atlas-sdk-ids", "dep:atlas-sysvar-id"]

[dependencies]
bv = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
atlas-sdk-ids = { workspace = true, optional = true }
atlas-sysvar-id = { workspace = true, optional = true }
