[package]
name = "atlas-time-utils"
description = "`std::time` utilities for Atlas"
documentation = "https://docs.rs/atlas-time-utils"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
