[package]
name = "atlas-sdk-wasm-js-tests"
description = "Tests for using the Atlas SDK Wasm JS crate"
documentation = "https://docs.rs/atlas-system-interface-wasm-js"
publish = false
version = "1.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
atlas-address = { workspace = true }
atlas-instruction = { workspace = true, features = ["std"] }
atlas-sdk-wasm-js = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[lints]
workspace = true
