[package]
name = "atlas-system-transaction"
description = "Functionality for creating system transactions."
documentation = "https://docs.rs/atlas-system-transaction"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-hash = { workspace = true }
atlas-keypair = { workspace = true }
atlas-message = { workspace = true }
atlas-pubkey = { workspace = true }
atlas-signer = { workspace = true }
atlas-system-interface = { workspace = true, features = ["bincode"] }
atlas-transaction = { workspace = true, features = ["bincode"] }
