[package]
name = "atlas-sdk-ids"
description = "Atlas SDK IDs"
documentation = "https://docs.rs/atlas-sdk-ids"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
atlas-pubkey = { workspace = true, default-features = false }

[lints]
workspace = true
